# Generated by Django 4.1.4 on 2023-01-17 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import newgen.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_id', models.IntegerField(default=newgen.models.Object.number, primary_key=True, serialize=False, verbose_name='Идентификационный номер')),
                ('location', models.CharField(max_length=150, null=True, verbose_name='Расположение')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('object_type', models.CharField(max_length=20, null=True, verbose_name='Тип объекта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен ли объект')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('tool_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер инструмента')),
                ('name', models.CharField(max_length=150, verbose_name='Название инструмента')),
            ],
            options={
                'verbose_name': 'Инструменты',
                'verbose_name_plural': 'Инструменты',
            },
        ),
        migrations.CreateModel(
            name='TotalSpendedTimeOnObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_fullname', models.CharField(max_length=150, verbose_name='ФИО')),
                ('object_name', models.CharField(max_length=150, verbose_name='Объект')),
                ('spended_time', models.FloatField(verbose_name='Затраченное время (часы)')),
            ],
            options={
                'verbose_name': 'Суммарное время на объекте в Excel',
                'verbose_name_plural': 'Суммарное время на объекте в Excel',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.IntegerField(default=newgen.models.Worker.number, primary_key=True, serialize=False, verbose_name='Номер сотрудника')),
                ('tabel', models.IntegerField(default=newgen.models.Worker.number, null=True, verbose_name='Табельный номер')),
                ('fullname', models.CharField(max_length=50, null=True, verbose_name='ФИО')),
                ('post', models.CharField(max_length=100, null=True, verbose_name='Должность')),
                ('coeff', models.FloatField(verbose_name='Коэффициент')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Монтажник',
                'verbose_name_plural': 'Монтажники',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('note_id', models.IntegerField(default=newgen.models.Work.number, primary_key=True, serialize=False, verbose_name='Номер записи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('spended_time', models.FloatField(max_length=25, verbose_name='Затраченное время')),
                ('comments', models.CharField(blank=True, max_length=300, verbose_name='Комментарии')),
                ('object_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newgen.object', verbose_name='Объект')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newgen.worker', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Выполненная работа',
                'verbose_name_plural': 'Выполненная работа',
            },
        ),
        migrations.CreateModel(
            name='ToolsReport',
            fields=[
                ('note_id', models.IntegerField(default=newgen.models.ToolsReport.number, primary_key=True, serialize=False, verbose_name='Номер записи')),
                ('date', models.DateField(verbose_name='Дата постановки на учёт')),
                ('tool_name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='newgen.tools', verbose_name='Название инструмента')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newgen.worker', verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Администрирование инструмента',
                'verbose_name_plural': 'Администрирование инструмента',
            },
        ),
        migrations.CreateModel(
            name='ToolsForwarding',
            fields=[
                ('note_id', models.IntegerField(default=newgen.models.ToolsForwarding.number, primary_key=True, serialize=False, verbose_name='Номер записи')),
                ('date', models.DateField(verbose_name='Дата постановки на учёт')),
                ('note', models.CharField(blank=True, max_length=150, verbose_name='Примечание')),
                ('tool_name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='newgen.tools', verbose_name='Название инструмента')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newgen.worker', verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'История перебросов',
                'verbose_name_plural': 'История перебросов',
            },
        ),
        migrations.CreateModel(
            name='TempToolTransfers',
            fields=[
                ('note_id', models.IntegerField(default=newgen.models.TempToolTransfers.number, primary_key=True, serialize=False, verbose_name='Номер записи')),
                ('note', models.CharField(blank=True, max_length=150, verbose_name='Примечание')),
                ('tool_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='newgen.tools', verbose_name='Название инструмента')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newgen.worker', verbose_name='Ответственное лицо')),
            ],
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('shedule_id', models.IntegerField(default=newgen.models.Shedule.number, primary_key=True, serialize=False, verbose_name='Номер записи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='newgen.worker', verbose_name='Бригадир')),
                ('target_objects', models.ManyToManyField(related_name='target_objects', to='newgen.object', verbose_name='Задачи')),
                ('workers', models.ManyToManyField(blank=True, related_name='workers', to='newgen.worker', verbose_name='Бригады')),
            ],
            options={
                'verbose_name': 'Расписание объектов',
                'verbose_name_plural': 'Расписания объектов',
            },
        ),
    ]
