# Generated by Django 4.1.4 on 2023-01-23 11:30

from django.db import migrations, models
import newgen.models


class Migration(migrations.Migration):

    dependencies = [
        ('newgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrgencyStatus',
            fields=[
                ('status_id', models.IntegerField(default=newgen.models.UrgencyStatus.number, primary_key=True, serialize=False, verbose_name='Номер записи')),
                ('status', models.CharField(max_length=30, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
            },
        ),
        migrations.AlterField(
            model_name='shedule',
            name='target_objects',
            field=models.ManyToManyField(related_name='target_objects', to='newgen.object', verbose_name='Планируемые объекты'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='workers', to='newgen.worker', verbose_name='Состав бригады'),
        ),
    ]
