# Generated by Django 4.1.4 on 2023-01-25 10:52

from django.db import migrations, models
import newgen.models


class Migration(migrations.Migration):

    dependencies = [
        ('newgen', '0003_email_openrequest_requestincheck_declinedrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('status_id', models.IntegerField(default=newgen.models.RequestStatus.number, primary_key=True, serialize=False, verbose_name='Номер статуса')),
                ('status', models.CharField(max_length=40, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
    ]
