# Generated by Django 4.1.4 on 2023-01-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgen', '0006_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно ли мыло'),
        ),
    ]
