# Generated by Django 4.1.4 on 2023-01-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgen', '0007_email_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='email',
            field=models.CharField(default='test', max_length=40, verbose_name='Email'),
        ),
    ]
