# Generated by Django 4.1.4 on 2023-02-07 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newgen', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newgen.openrequest'),
        ),
    ]
