# Generated by Django 4.1.4 on 2023-02-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgen', '0010_alter_comment_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='closedrequest',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='closedrequest',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='closedrequest',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='closedrequest',
            name='problem_description',
        ),
        migrations.RemoveField(
            model_name='closedrequest',
            name='time',
        ),
        migrations.RemoveField(
            model_name='closedrequest',
            name='worker_id',
        ),
        migrations.AddField(
            model_name='closedrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='closedrequest',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/2023/02/17/', verbose_name='Фото 1'),
        ),
        migrations.AddField(
            model_name='closedrequest',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/2023/02/17/', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='closedrequest',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/2023/02/17/', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='closedrequest',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ответственный(е)'),
        ),
        migrations.AlterField(
            model_name='closedrequest',
            name='rating',
            field=models.IntegerField(blank=True, verbose_name='Качество обслуживания'),
        ),
    ]
