# Generated by Django 4.1.4 on 2023-02-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgen', '0011_remove_closedrequest_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declinedrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='declinedrequest',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='declinedrequest',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='declinedrequest',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='declinedrequest',
            name='problem_description',
        ),
        migrations.RemoveField(
            model_name='declinedrequest',
            name='time',
        ),
        migrations.RemoveField(
            model_name='declinedrequest',
            name='worker_id',
        ),
        migrations.AddField(
            model_name='declinedrequest',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответственный(е)'),
        ),
        migrations.AlterField(
            model_name='closedrequest',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='closedrequest',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Качество обслуживания'),
        ),
        migrations.AlterField(
            model_name='closedrequest',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответственный(е)'),
        ),
    ]
