# Generated by Django 4.1.4 on 2023-02-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgen', '0012_remove_declinedrequest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedrequest',
            name='client_comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Комментарий клиента'),
        ),
        migrations.AlterField(
            model_name='closedrequest',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Комментарий исполнителя'),
        ),
        migrations.AlterField(
            model_name='closedrequest',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/2023/02/21/', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='closedrequest',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/2023/02/21/', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='closedrequest',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/2023/02/21/', verbose_name='Фото 3'),
        ),
    ]
